### ISSUE TITLE
sha1

### ISSUE THREAD

**Issue by RogierQ** [andresrdgz/node-red-contrib-crypto-js-mod#1]
In the example you say that sha1 is included in the digest node
But when i install it i cannot find the sha1 only the sha3
is this correct?

thanks
Rogier

**Comment by andresrdgz** [comment]
Ask the original developer in
https://github.com/baumblatt/node-red-contrib-crypto-js

This repo is only a copy of that for personal testing purposes with no maintenance.

Sorry.
